# 服务端口
server:
  port: 8098

# 本地模型服务地址
url:
  fastapi: http://127.0.0.1:8000
  flask: ""

spring:
  application:
    name: model-service # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos